/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__utils__MBezierUtils
#define __PYX_HAVE__utils__MBezierUtils

#include "Python.h"

#ifndef __PYX_HAVE_API__utils__MBezierUtils

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int INTERPOLATION_MMD_MAX;
__PYX_EXTERN_C PyObject *LINEAR_MMD_INTERPOLATION;
__PYX_EXTERN_C PyObject *R_x1_idxs;
__PYX_EXTERN_C PyObject *R_y1_idxs;
__PYX_EXTERN_C PyObject *R_x2_idxs;
__PYX_EXTERN_C PyObject *R_y2_idxs;
__PYX_EXTERN_C PyObject *MX_x1_idxs;
__PYX_EXTERN_C PyObject *MX_y1_idxs;
__PYX_EXTERN_C PyObject *MX_x2_idxs;
__PYX_EXTERN_C PyObject *MX_y2_idxs;
__PYX_EXTERN_C PyObject *MY_x1_idxs;
__PYX_EXTERN_C PyObject *MY_y1_idxs;
__PYX_EXTERN_C PyObject *MY_x2_idxs;
__PYX_EXTERN_C PyObject *MY_y2_idxs;
__PYX_EXTERN_C PyObject *MZ_x1_idxs;
__PYX_EXTERN_C PyObject *MZ_y1_idxs;
__PYX_EXTERN_C PyObject *MZ_x2_idxs;
__PYX_EXTERN_C PyObject *MZ_y2_idxs;
__PYX_EXTERN_C PyObject *BZ_TYPE_MX;
__PYX_EXTERN_C PyObject *BZ_TYPE_MY;
__PYX_EXTERN_C PyObject *BZ_TYPE_MZ;
__PYX_EXTERN_C PyObject *BZ_TYPE_R;

#endif /* !__PYX_HAVE_API__utils__MBezierUtils */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initMBezierUtils(void);
#else
PyMODINIT_FUNC PyInit_MBezierUtils(void);
#endif

#endif /* !__PYX_HAVE__utils__MBezierUtils */
