"""Subclass of VmdConverterFrame, which is generated by wxFormBuilder."""

import wx
import VmdConverterForm

# Implementing VmdConverterFrame
class VmdConverterProject( VmdConverterForm.VmdConverterFrame ):
	def __init__( self, parent ):
		VmdConverterForm.VmdConverterFrame.__init__( self, parent )

	# Handlers for VmdConverterFrame events.
	def exec( self, event ):
		# TODO: Implement exec
		pass


