"""Subclass of VmdSizingForm3, which is generated by wxFormBuilder."""

import wx
import VmdSizingForm3

# Implementing VmdSizingForm3
class VmdSizingProject3( VmdSizingForm3.VmdSizingForm3 ):
	def __init__( self, parent ):
		VmdSizingForm3.VmdSizingForm3.__init__( self, parent )

