"""Subclass of Frame, which is generated by wxFormBuilder."""

import wx
import VmdSizingForm

# Implementing Frame
class VmdSizingProjectFrame( VmdSizingForm.Frame ):
	def __init__( self, parent ):
		VmdSizingForm.Frame.__init__( self, parent )

